### ISSUE TITLE
Sync with pyOTDR

### ISSUE THREAD

**Issue by dsshap** [sid5432/rbOTDR#1]
Hi!

This is pretty awesome. I see that pyOTDR is a bit more maintained, any plans to port the latest here?

**Comment by sid5432** [comment]
Thank you for your kind words. As far as "decoding" the SOR file structure goes, I think the Ruby code is in sync with the Python code. The other features are a different matter. Unfortunately I don't have any immediately plans for making any changes/improvements to the Ruby code. Sorry.

**Comment by dsshap** [comment]
Got it. I will take a look to see what the diverging features are.

In the meantime, could you provide a gemfile or list of gem versions you are using?

I ran into a couple of version issues that I got resolved but when running tests, there were some failures.

```Loaded suite tests/runall
Started
F
===================================================================================================================================================================
     48:     trace = []
     49:     status = sorparse.run(results, trace, debug=true)
     50:     
  => 51:     assert results['Cksum']['checksum_ours'] == digest
     52:     
     53:     # SOR version 2
     54:     filename = __dir__+"/../data/sample1310_lowDR.sor"
/Users/dsshap/Fiber/rbOTDR/tests/test_cksum.rb:51:in `test_cksum'
Failure: test_cksum(CB_test_cksum): <false> is not true.
===================================================================================================================================================================
.....F
===================================================================================================================================================================
     51:   end
     52:   
     53:   def test_read1
  => 54:     mycompare "demo_ab.sor"
     55:     return
     56:   end
     57:   
/Users/dsshap/Fiber/rbOTDR/tests/test_read.rb:54:in `test_read1'
/Users/dsshap/Fiber/rbOTDR/tests/test_read.rb:50:in `mycompare'
Failure: test_read1(CB_test_read): <false> is not true.
===================================================================================================================================================================
F
===================================================================================================================================================================
     56:   end
     57:   
     58:   def test_read2
  => 59:     mycompare("sample1310_lowDR.sor")
     60:     return
     61:   end
     62:   
/Users/dsshap/Fiber/rbOTDR/tests/test_read.rb:59:in `test_read2'
/Users/dsshap/Fiber/rbOTDR/tests/test_read.rb:50:in `mycompare'
Failure: test_read2(CB_test_read): <false> is not true.
===================================================================================================================================================================
F
===================================================================================================================================================================
     61:   end
     62:   
     63:   def test_read3
  => 64:     mycompare("M200_Sample_005_S13.sor")
     65:     return
     66:   end
     67:   
/Users/dsshap/Fiber/rbOTDR/tests/test_read.rb:64:in `test_read3'
/Users/dsshap/Fiber/rbOTDR/tests/test_read.rb:50:in `mycompare'
Failure: test_read3(CB_test_read): <false> is not true.
===================================================================================================================================================================

Finished in 0.591852 seconds.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
9 tests, 35 assertions, 4 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
55.5556% passed
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
15.21 tests/s, 59.14 assertions/s```

**Comment by sid5432** [comment]
The gems that are none standard are "crc" and 'json'. The only other 'require'd gems are 'logger' and 'date'. (I currently have ruby 2.7.0p0 from Ubuntu 20.04). If you want to run the tests (in the tests folder), you'll need the 'test-unit' and 'digest-crc' gems.

**Comment by dsshap** [comment]
Strange, `date` was throwing an error on ruby 2.6.3, not an issue on 2.7.

Seeing test checksum errors. Both `demo_ab.sor` and `sample1310_lowDR.sor` are outputting different values from what is hardcoded in the test. I am running this on MacOS 10.15.5

```
demo_ab.sor
  "Cksum": {
    "checksum_ours": 24995,
    "checksum": 38827,
    "match": false
  }

sample1310_lowDR.sor
"Cksum": {
    "checksum_ours": 48376,
    "checksum": 59892,
    "match": false
  }
```


I am not seeing much difference between your python lib and this one.
